<?xml version="1.0"?>
<!-- From Linorobot2, mounted above Camera Bracket and called by mtbc1_sensors.urdf.xacro -->
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  
  <xacro:macro name="imu">

    <link name="imu_link"/> 
   
    <joint name="imu_to_base_joint" type="fixed">
      <parent link="base_link"/>
      <child link="imu_link"/>
      <origin xyz="0 0 ${imu_z_offset + shelf_zoff}" rpy="0 0 0"/>
    </joint>

  </xacro:macro> 

</robot>   