<?xml version="1.0"?>
<robot name="mtbc1" xmlns:xacro="http://ros.org/wiki/xacro">

<!-- 
<xacro:include filename="(find mtbc1_description)/urdf/common_properties.urdf.xacro" />
<xacro:include filename="(find mtbc1_description)/urdf/mtbc1_base.urdf.xacro" />
<xacro:include filename="(find mtbc1_description)/urdf/mtbc1_sensor.urdf.xacro" />
<xacro:include filename="(find mtbc1_description)/urdf/stacks/circlesc1.urdf.xacro />
-->

  <!-- Define robot constants -->
  <xacro:property name="base_width" value="0.31"/>
  <xacro:property name="base_length" value="0.42"/>
  <xacro:property name="base_height" value="0.18"/>

  <xacro:property name="c1base_len" value="0.065"/>
  <xacro:property name="c1base_rad" value="0.1915"/>

  <xacro:property name="wheel_radius" value="0.10"/>
  <xacro:property name="wheel_width" value="0.04"/>
  <xacro:property name="wheel_ygap" value="0.025"/>
  <xacro:property name="wheel_zoff" value="0.05"/>
  <xacro:property name="wheel_xoff" value="0.12"/>

  <xacro:property name="c1wheel_radius" value="0.0305"/>
  <xacro:property name="c1wheel_width" value="0.027"/>
  <xacro:property name="c1wheel_ygap" value="0.033"/>
  <xacro:property name="c1wheel_zoff" value="0.015"/>
  <xacro:property name="c1wheel_xoff" value="0.00"/>

  <!-- <xacro:property name="caster_xoff" value="0.14"/> -->
  <!-- <xacro:property name="c1caster_xoff" value="0.123"/> -->
  <xacro:property name="c1fcaster_xoff" value="0.123"/>
  <xacro:property name="c1rcaster_xoff" value="0.145"/>

  <!--IMU Properties-->
  <xacro:property name="imu_zoff" value="0.266"/>
  
  <!-- Robot Base -->
  <link name="base_link">
    <visual>
      <geometry>
        <!--<box size="${base_length} ${base_width} ${base_height}"/> -->
        <cylinder length="${c1base_len}" radius="${c1base_rad}"/> 
      </geometry>
      <!--<material name="Cyan"> -->
      <!-- <color rgba="0 1.0 1.0 1.0"/> -->
      <material name="White">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </visual>
  </link>
  
   <!-- Robot Footprint -->
   <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <!-- <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/> -->
    <origin xyz="0.0 0.0 ${-(c1wheel_radius+c1wheel_zoff)}" rpy="0 0 0"/>
  </joint>

  <!-- Wheels -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <!-- <cylinder radius="${wheel_radius}" length="${wheel_width}"/> -->
            <cylinder radius="${c1wheel_radius}" length="${c1wheel_width}"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>
    </link>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <!-- <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/> -->
      <origin xyz="${x_reflect*c1wheel_xoff} ${y_reflect*(c1base_rad-c1wheel_ygap)} ${-c1wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel prefix="drivewhl_l" x_reflect="-1" y_reflect="1" />
  <xacro:wheel prefix="drivewhl_r" x_reflect="-1" y_reflect="-1" />
  
  <!-- Caster Front Wheel -->
  <link name="front_caster">
    <visual>
      <geometry>
        <!-- <sphere radius="${(wheel_radius+wheel_zoff-(base_height/2))}"/> -->
        <sphere radius="${(c1wheel_radius+c1wheel_zoff-(c1base_len/2))}"/>
      </geometry>
       <!-- <material name="Cyan"> -->
       <!-- <color rgba="0 1.0 1.0 1.0"/> -->
        <material name="White">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </visual>
  </link>
 
  <joint name="casterf_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_caster"/>
    <!-- <origin xyz="${caster_xoff} 0.0 ${-(base_height/2)}" rpy="0 0 0"/> -->
    <origin xyz="${c1fcaster_xoff} 0.0 ${-(c1base_len/2)}" rpy="0 0 0"/>
  </joint> 

  <!-- Caster Rear Wheel -->
  <link name="rear_caster">
    <visual>
      <geometry>
        <!-- <sphere radius="${(wheel_radius+wheel_zoff-(base_height/2))}"/> -->
        <sphere radius="${(c1wheel_radius+c1wheel_zoff-(c1base_len/2))}"/>
      </geometry>
       <!-- <material name="Cyan"> -->
       <!-- <color rgba="0 1.0 1.0 1.0"/> -->
        <material name="White">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </visual>
  </link>
 
  <joint name="casterr_joint" type="fixed">
    <parent link="base_link"/>
    <child link="rear_caster"/>
    <!-- <origin xyz="${caster_xoff} 0.0 ${-(base_height/2)}" rpy="0 0 0"/> -->
    <origin xyz="${-c1rcaster_xoff} 0.0 ${-(c1base_len/2)}" rpy="0 0 0"/>
  </joint> 

</robot>